# Header
menu:
  Home: /
  Archives: /archives
# rss: /atom.xml

# Content
excerpt_link: read more

# Favicon
favicon: /favicon.ico

# Settings toggle
settings: true

# Code CSS toggle
highlight: true

# Word count (needs hexo-wordcount)
word_count: false

# Google Analytics
google_analytics:
  enable: true
  acct: "G-RZ1WB2RQDK"

# IntenseDebate ID
intensedebate:
  enable: false
  acct: "000000000000000000000"
